# -*- coding: utf-8 -*-
"""Perceptron

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13O8x0B8SU0WnVV5WU1z--cUAF9gNLur-
"""

# ============================================================
# EXERCISE 1 - PERCEPTRON
# Banknote Authentication Dataset
# Google Colab Version
# ============================================================

# Install UCI dataset package
!pip -q install ucimlrepo


# ============================================================
# IMPORT LIBRARIES
# ============================================================

import numpy as np
import pandas as pd

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


# ============================================================
# LOAD BANKNOTE AUTHENTICATION DATASET
# ============================================================

print("=" * 65)
print("LOADING BANKNOTE AUTHENTICATION DATASET")
print("=" * 65)

# UCI Dataset ID = 267
banknote = fetch_ucirepo(id=267)

# Get features and target
X_df = banknote.data.features
y_df = banknote.data.targets

# Convert to NumPy
X = X_df.values
y = y_df.values.ravel()

# Rename features for our program
feature_names = [
    "Variance",
    "Skewness",
    "Curtosis",
    "Entropy"
]

print("\nDataset loaded successfully!")

print("\nDataset Shape:")
print("X =", X.shape)
print("y =", y.shape)

print("\nFirst 5 rows:")
print(X_df.head())

print("\nTarget values:")
print(np.unique(y))

print("\nClass distribution:")
print(pd.Series(y).value_counts())


# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


# ============================================================
# FEATURE NORMALIZATION
# ============================================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train_raw)
X_test = scaler.transform(X_test_raw)

print("\nTraining samples:", len(X_train))
print("Testing samples :", len(X_test))


# ============================================================
# CUSTOM SINGLE-LAYER PERCEPTRON
# ============================================================

class Perceptron:

    def __init__(
        self,
        learning_rate=0.01,
        max_epochs=100
    ):

        self.learning_rate = learning_rate
        self.max_epochs = max_epochs

        self.weights = None
        self.bias = 0

        self.epochs = 0
        self.converged = False

    # --------------------------------------------------------
    # STEP ACTIVATION FUNCTION
    # --------------------------------------------------------

    def step(self, z):

        if z >= 0:
            return 1
        else:
            return 0

    # --------------------------------------------------------
    # TRAINING USING PERCEPTRON LEARNING RULE
    # --------------------------------------------------------

    def fit(self, X, y, order=None):

        n_samples, n_features = X.shape

        # Initialize weights and bias
        self.weights = np.zeros(n_features)
        self.bias = 0

        self.converged = False

        # Training order
        if order is None:
            order = np.arange(n_samples)

        # Epoch loop
        for epoch in range(
            1,
            self.max_epochs + 1
        ):

            errors = 0

            # Process samples
            for i in order:

                x = X[i]
                target = y[i]

                # Weighted sum
                z = (
                    np.dot(
                        x,
                        self.weights
                    )
                    + self.bias
                )

                # Step activation
                prediction = self.step(z)

                # Error
                error = target - prediction

                # Perceptron learning rule
                self.weights += (
                    self.learning_rate
                    * error
                    * x
                )

                self.bias += (
                    self.learning_rate
                    * error
                )

                if error != 0:
                    errors += 1

            self.epochs = epoch

            # Check convergence
            if errors == 0:

                self.converged = True
                break

        return self

    # --------------------------------------------------------
    # PREDICTION
    # --------------------------------------------------------

    def predict(self, X):

        predictions = []

        for x in X:

            z = (
                np.dot(
                    x,
                    self.weights
                )
                + self.bias
            )

            prediction = self.step(z)

            predictions.append(prediction)

        return np.array(predictions)

    # --------------------------------------------------------
    # WEIGHTED SUM
    # --------------------------------------------------------

    def weighted_sum(self, X):

        return (
            np.dot(
                X,
                self.weights
            )
            + self.bias
        )


# ============================================================
# HELPER FUNCTION
# ============================================================

def train_perceptron(
    Xtr,
    ytr,
    Xte,
    yte,
    order=None
):

    model = Perceptron(
        learning_rate=0.01,
        max_epochs=100
    )

    model.fit(
        Xtr,
        ytr,
        order
    )

    predictions = model.predict(Xte)

    accuracy = accuracy_score(
        yte,
        predictions
    )

    return (
        model,
        predictions,
        accuracy
    )


# ============================================================
# 1. BANKNOTE CLASSIFICATION
# ============================================================

def banknote_classification():

    print("\n" + "=" * 65)
    print("1. BANKNOTE CLASSIFICATION USING PERCEPTRON")
    print("=" * 65)

    (
        model,
        predictions,
        accuracy
    ) = train_perceptron(
        X_train,
        y_train,
        X_test,
        y_test
    )

    weighted_sum = model.weighted_sum(
        X_test
    )

    result = pd.DataFrame({

        "Actual":
            y_test,

        "Predicted":
            predictions,

        "Weighted Sum":
            np.round(
                weighted_sum,
                4
            )
    })

    print("\nFinal Weights:")

    for name, weight in zip(
        feature_names,
        model.weights
    ):

        print(
            f"{name:12s} : {weight:.4f}"
        )

    print(
        "\nBias:",
        round(
            model.bias,
            4
        )
    )

    print(
        "\nEpochs:",
        model.epochs
    )

    print(
        "Converged:",
        model.converged
    )

    print(
        "\nAccuracy:",
        round(
            accuracy * 100,
            2
        ),
        "%"
    )

    print("\nPrediction Results:")
    print(
        result.to_string(
            index=False
        )
    )


# ============================================================
# 2. DECISION BOUNDARY EXPLORER
# ============================================================

def decision_boundary():

    print("\n" + "=" * 65)
    print("2. DECISION BOUNDARY EXPLORER")
    print("=" * 65)

    print("\nAvailable Features:")

    for i, name in enumerate(
        feature_names
    ):

        print(
            f"{i + 1}. {name}"
        )

    try:

        f1 = int(
            input(
                "\nSelect first feature (1-4): "
            )
        ) - 1

        f2 = int(
            input(
                "Select second feature (1-4): "
            )
        ) - 1

    except:

        print("Invalid input!")
        return

    if (
        f1 < 0
        or f1 > 3
        or f2 < 0
        or f2 > 3
        or f1 == f2
    ):

        print(
            "Please select two different features!"
        )

        return

    selected = [
        f1,
        f2
    ]

    Xtr = X_train[:, selected]
    Xte = X_test[:, selected]

    (
        model,
        predictions,
        accuracy
    ) = train_perceptron(
        Xtr,
        y_train,
        Xte,
        y_test
    )

    w1 = model.weights[0]
    w2 = model.weights[1]
    b = model.bias

    print(
        "\nSelected Features:"
    )

    print(
        feature_names[f1],
        "+",
        feature_names[f2]
    )

    print(
        "\nWeights:",
        np.round(
            model.weights,
            4
        )
    )

    print(
        "Bias:",
        round(
            b,
            4
        )
    )

    print(
        "\nDecision Boundary:"
    )

    print(
        f"{w1:.4f} × {feature_names[f1]} + "
        f"{w2:.4f} × {feature_names[f2]} + "
        f"{b:.4f} = 0"
    )

    print(
        "\nAccuracy:",
        round(
            accuracy * 100,
            2
        ),
        "%"
    )


# ============================================================
# 3. FEATURE PAIR SEPARABILITY
# ============================================================

def feature_pair_separability():

    print("\n" + "=" * 65)
    print("3. FEATURE PAIR SEPARABILITY CHALLENGE")
    print("=" * 65)

    results = []

    # Test every possible pair
    for i in range(4):

        for j in range(
            i + 1,
            4
        ):

            selected = [
                i,
                j
            ]

            Xtr = X_train[:, selected]
            Xte = X_test[:, selected]

            (
                model,
                predictions,
                accuracy
            ) = train_perceptron(
                Xtr,
                y_train,
                Xte,
                y_test
            )

            misclassified = np.sum(
                predictions != y_test
            )

            results.append({

                "Feature Pair":
                    feature_names[i]
                    + " + "
                    + feature_names[j],

                "Epochs":
                    model.epochs,

                "Accuracy (%)":
                    round(
                        accuracy * 100,
                        2
                    ),

                "Misclassified":
                    misclassified,

                "Converged":
                    model.converged
            })

    result = pd.DataFrame(
        results
    )

    result = result.sort_values(
        by="Accuracy (%)",
        ascending=False
    )

    print(
        result.to_string(
            index=False
        )
    )

    print(
        "\nBest Feature Pair:"
    )

    print(
        result.iloc[0]["Feature Pair"]
    )


# ============================================================
# 4. TRAINING SAMPLE ORDER CHALLENGE
# ============================================================

def sample_order_challenge():

    print("\n" + "=" * 65)
    print("4. TRAINING SAMPLE ORDER CHALLENGE")
    print("=" * 65)

    n = len(X_train)

    rng = np.random.default_rng(42)

    # Different sample orders
    class_0 = np.where(
        y_train == 0
    )[0]

    class_1 = np.where(
        y_train == 1
    )[0]

    orders = {

        "Original":
            np.arange(n),

        "Reverse":
            np.arange(n)[::-1],

        "Random":
            rng.permutation(n),

        "Class-wise":
            np.concatenate([
                class_0,
                class_1
            ])
    }

    results = []

    for name, order in orders.items():

        (
            model,
            predictions,
            accuracy
        ) = train_perceptron(
            X_train,
            y_train,
            X_test,
            y_test,
            order
        )

        results.append({

            "Order":
                name,

            "Epochs":
                model.epochs,

            "Accuracy (%)":
                round(
                    accuracy * 100,
                    2
                ),

            "Bias":
                round(
                    model.bias,
                    4
                ),

            "Converged":
                model.converged
        })

    result = pd.DataFrame(
        results
    )

    print(
        result.to_string(
            index=False
        )
    )

    print(
        "\nObservation:"
    )

    print(
        "Changing the training sample order can "
        "change convergence speed and final weights."
    )


# ============================================================
# 5. BORDERLINE SAMPLE DETECTOR
# ============================================================

def borderline_detector():

    print("\n" + "=" * 65)
    print("5. BORDERLINE SAMPLE DETECTOR")
    print("=" * 65)

    (
        model,
        predictions,
        accuracy
    ) = train_perceptron(
        X_train,
        y_train,
        X_test,
        y_test
    )

    # Calculate weighted sums
    weighted_sum = model.weighted_sum(
        X_test
    )

    # Distance from decision boundary
    distance = np.abs(
        weighted_sum
    )

    # Five closest samples
    indices = np.argsort(
        distance
    )[:5]

    result = pd.DataFrame({

        "Sample":
            indices + 1,

        "Actual":
            y_test[
                indices
            ],

        "Predicted":
            predictions[
                indices
            ],

        "Weighted Sum":
            np.round(
                weighted_sum[
                    indices
                ],
                5
            ),

        "Distance":
            np.round(
                distance[
                    indices
                ],
                5
            )
    })

    print(
        "\nTop 5 Borderline Samples:"
    )

    print(
        result.to_string(
            index=False
        )
    )

    print(
        "\nSmaller distance = closer to "
        "the decision boundary."
    )


# ============================================================
# 6. XOR LIMITATION DEMONSTRATOR
# ============================================================

def xor_limitation():

    print("\n" + "=" * 65)
    print("6. XOR LIMITATION DEMONSTRATOR")
    print("=" * 65)

    # Logic gate inputs
    X_logic = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

    logic_datasets = {

        "AND":
            np.array([
                0, 0, 0, 1
            ]),

        "OR":
            np.array([
                0, 1, 1, 1
            ]),

        "NAND":
            np.array([
                1, 1, 1, 0
            ]),

        "XOR":
            np.array([
                0, 1, 1, 0
            ])
    }

    for name, target in logic_datasets.items():

        model = Perceptron(
            learning_rate=0.1,
            max_epochs=20
        )

        model.fit(
            X_logic,
            target
        )

        predictions = model.predict(
            X_logic
        )

        accuracy = accuracy_score(
            target,
            predictions
        )

        print(
            "\n------------------------------"
        )

        print(
            name
        )

        print(
            "------------------------------"
        )

        print(
            "Weights:",
            np.round(
                model.weights,
                4
            )
        )

        print(
            "Bias:",
            round(
                model.bias,
                4
            )
        )

        print(
            "Predictions:",
            predictions
        )

        print(
            "Accuracy:",
            round(
                accuracy * 100,
                2
            ),
            "%"
        )

        print(
            "Converged:",
            model.converged
        )

        if name == "XOR":

            print(
                "Result: XOR is NOT linearly separable."
            )

            print(
                "A single-layer perceptron cannot "
                "correctly learn XOR."
            )

        else:

            print(
                "Result:",
                name,
                "is linearly separable."
            )


# ============================================================
# 7. FEATURE REMOVAL CHALLENGE
# ============================================================

def feature_removal():

    print("\n" + "=" * 65)
    print("7. PERCEPTRON FEATURE REMOVAL CHALLENGE")
    print("=" * 65)

    # Full model
    (
        full_model,
        full_predictions,
        full_accuracy
    ) = train_perceptron(
        X_train,
        y_train,
        X_test,
        y_test
    )

    results = []

    # Remove one feature at a time
    for remove in range(4):

        keep = [
            i
            for i in range(4)
            if i != remove
        ]

        Xtr = X_train[
            :,
            keep
        ]

        Xte = X_test[
            :,
            keep
        ]

        (
            model,
            predictions,
            accuracy
        ) = train_perceptron(
            Xtr,
            y_train,
            Xte,
            y_test
        )

        accuracy_drop = (
            full_accuracy
            - accuracy
        ) * 100

        results.append({

            "Removed Feature":
                feature_names[remove],

            "Accuracy (%)":
                round(
                    accuracy * 100,
                    2
                ),

            "Accuracy Drop (%)":
                round(
                    accuracy_drop,
                    2
                ),

            "Epochs":
                model.epochs
        })

    result = pd.DataFrame(
        results
    )

    print(
        "\nAccuracy with all features:",
        round(
            full_accuracy * 100,
            2
        ),
        "%"
    )

    print(
        "\nFeature Removal Results:"
    )

    print(
        result.to_string(
            index=False
        )
    )

    # Find most important feature
    worst = result.loc[
        result[
            "Accuracy Drop (%)"
        ].idxmax()
    ]

    print(
        "\nMost influential feature:",
        worst[
            "Removed Feature"
        ]
    )


# ============================================================
# 8. PERCEPTRON CLASSIFICATION REPORT
# ============================================================

def classification_report_menu():

    print("\n" + "=" * 65)
    print("8. PERCEPTRON CLASSIFICATION REPORT")
    print("=" * 65)

    (
        model,
        predictions,
        accuracy
    ) = train_perceptron(
        X_train,
        y_train,
        X_test,
        y_test
    )

    weighted_sum = model.weighted_sum(
        X_test
    )

    misclassified = np.sum(
        predictions != y_test
    )

    # Borderline threshold
    borderline = np.sum(
        np.abs(
            weighted_sum
        ) < 0.1
    )

    print(
        "\nDataset:"
        " Banknote Authentication"
    )

    print(
        "Training samples:",
        len(X_train)
    )

    print(
        "Testing samples:",
        len(X_test)
    )

    print(
        "\nFeatures:"
    )

    for feature in feature_names:

        print(
            " -",
            feature
        )

    print(
        "\nLearning Rate:",
        model.learning_rate
    )

    print(
        "Maximum Epochs:",
        model.max_epochs
    )

    print(
        "\nActual Epochs:",
        model.epochs
    )

    print(
        "Converged:",
        model.converged
    )

    print(
        "\nFinal Weights:"
    )

    for name, weight in zip(
        feature_names,
        model.weights
    ):

        print(
            f"{name:12s}: {weight:.4f}"
        )

    print(
        "\nBias:",
        round(
            model.bias,
            4
        )
    )

    print(
        "\nTest Accuracy:",
        round(
            accuracy * 100,
            2
        ),
        "%"
    )

    print(
        "Misclassified Samples:",
        misclassified
    )

    print(
        "Borderline Samples:",
        borderline
    )


# ============================================================
# MAIN MENU
# ============================================================

def main():

    while True:

        print("\n")
        print("=" * 65)
        print("       BANKNOTE AUTHENTICATION - PERCEPTRON")
        print("=" * 65)

        print(
            "1. Banknote Classification using Perceptron"
        )

        print(
            "2. Decision Boundary Explorer"
        )

        print(
            "3. Feature Pair Separability Challenge"
        )

        print(
            "4. Training Sample Order Challenge"
        )

        print(
            "5. Borderline Sample Detector"
        )

        print(
            "6. XOR Limitation Demonstrator"
        )

        print(
            "7. Perceptron Feature Removal Challenge"
        )

        print(
            "8. Perceptron Classification Report"
        )

        print(
            "9. Exit"
        )

        choice = input(
            "\nEnter your choice (1-9): "
        )

        if choice == "1":

            banknote_classification()

        elif choice == "2":

            decision_boundary()

        elif choice == "3":

            feature_pair_separability()

        elif choice == "4":

            sample_order_challenge()

        elif choice == "5":

            borderline_detector()

        elif choice == "6":

            xor_limitation()

        elif choice == "7":

            feature_removal()

        elif choice == "8":

            classification_report_menu()

        elif choice == "9":

            print(
                "\nProgram terminated."
            )

            break

        else:

            print(
                "\nInvalid choice! "
                "Please enter a number from 1 to 9."
            )


# ============================================================
# RUN PROGRAM
# ============================================================

main()